# Generated by Django 5.0.1 on 2024-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCode', models.CharField(default='rtqg60sBh5lObKKo', max_length=16)),
                ('ip', models.CharField(default='000.000.000.000', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visits', models.IntegerField(default=1)),
            ],
        ),
    ]
