# Generated by Django 5.0.1 on 2024-02-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='000.000.000.000', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visits',
            new_name='pageCount',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='userCode',
        ),
        migrations.AddField(
            model_name='visitor',
            name='sessionCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='prypQRhkPNbhuYd4', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='sessions',
            field=models.ManyToManyField(to='visitor.session'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerCode', models.CharField(default='J7ankGwaFax2iqgT', max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visitorAccounts', models.ManyToManyField(to='visitor.visitor')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitor.user')),
            ],
        ),
    ]
