# Generated by Django 5.0.1 on 2024-02-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_session_user_rename_visits_visitor_pagecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='tbWlNgpbU2R6W4wSutygOlJERcGSk6kuvibI', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='BoGXVjAxnoz8fzdX', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='3BcpETIh9OmkiRxI', max_length=16, unique=True),
        ),
    ]
