# Generated by Django 5.0.1 on 2024-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_session_session_key_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='EiOhojGkks7vOviC', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='InijRLm7YQZN1e2FsENBqZSJvaTzuPHArO8M', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='QW9FkUN35pkDMDfe', max_length=16, unique=True),
        ),
    ]
