# Generated by Django 5.0.1 on 2024-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='zRgpiLKAQPvBnQLR', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='cUAEO75dnMNtO1wPSJuepZCNVyc1spRQCgpP', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='xDtWMgzvUDjBPQho', max_length=16, unique=True),
        ),
    ]
