# Generated by Django 5.0.1 on 2024-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='spDUi0QGDbUPTLsZ', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='GY2zS7snX12NXn3wghtnOmwglXcsgaoDA8tQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='Jn55wBYHPJCt6wJF', max_length=16, unique=True),
        ),
    ]
