# Generated by Django 5.0.1 on 2024-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='UAcUfTYpO9WfwykU', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='2FHOsvzg9kluRNxLyxkUW1vWhRG4TvpEtfC0', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='enOJmwLRd1bjJFCx', max_length=16, unique=True),
        ),
    ]
