# Generated by Django 5.0.1 on 2024-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='UuQgDYZJeseeFSfg', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='tMsWMpDdwU3w0UKKMM4pjOpXtpcIgClf71NF', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='5RQbbfYBwzxarbOP', max_length=16, unique=True),
        ),
    ]
