# Generated by Django 5.0.1 on 2024-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='kIQVqQ4MBSOSghLu', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='Mk5r4R8su9WjLHUJf4KNuHbiD8o3TRt2E5Fn', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='JUlglU6ZSHLhrgOU', max_length=16, unique=True),
        ),
    ]
