# Generated by Django 5.0.1 on 2024-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='oSawd4IpcwPRzKXC', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='oNoRjVNwajgDpRh7BmVFNoaxOVZ5gPUdUkmH', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='TsHvrgumGHIVHmhs', max_length=16, unique=True),
        ),
    ]
