# Generated by Django 5.0.2 on 2024-03-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerCode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userProfile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='visitorAccounts',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='5u2WkhqLPGzq3Qdq', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='visitor_ids',
            field=models.ManyToManyField(default=None, null=True, to='visitor.visitor'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='visitor.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='W8F8ogBYzJT0NJ5hiOr1obGVaPY4w3bvmaw7', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='bwZ1NCpUuPp3WurFyfb7Ce0W', max_length=16, unique=True),
        ),
    ]
