# Generated by Django 5.0.1 on 2024-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_alter_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(default='AfNTXhmQSRYRpidv', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='9GUkWhWSCRZaqaaRUnNV8t8HNlLnPJqDeLOE', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='aXjGrAmgJbpWbUYK', max_length=16, unique=True),
        ),
    ]
