# Generated by Django 5.0.2 on 2024-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_remove_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='9UqT9AKq4uxEpeSf', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(default='A5s4SqIfDqfP2RWpbNXIcsBXgFRJGsy9nCQx', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorCode',
            field=models.CharField(default='za1OFSXvonh4TlurjoES2UR7', max_length=16, unique=True),
        ),
    ]
