# Generated by Django 5.0.1 on 2024-02-06 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 22, 43, 3, 352627)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='description', max_length=500),
        ),
    ]
