# Generated by Django 5.0.1 on 2024-02-07 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_item_name_alter_item_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 0, 41, 23, 949374)),
        ),
    ]
