# Generated by Django 5.0.1 on 2024-02-20 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_sku_alter_item_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 33, 35, 698923)),
        ),
    ]
