# Generated by Django 5.0.1 on 2024-02-20 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promo_alter_item_created_on_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='applicable_items',
            field=models.ManyToManyField(to='shop.item'),
        ),
        migrations.AddField(
            model_name='promo',
            name='can_combine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.TextField(default='Discount'),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(default='percent', max_length=12),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 48, 26, 676696)),
        ),
    ]
