# Generated by Django 5.0.1 on 2024-02-21 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promo_applicable_items_promo_can_combine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 18, 21, 38, 558390)),
        ),
    ]
