# Generated by Django 5.0.1 on 2024-02-21 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_item_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 18, 24, 15, 801462)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='cart', max_length=10),
        ),
    ]
