# Generated by Django 5.0.1 on 2024-02-21 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_customer_alter_item_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promos',
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 18, 36, 44, 842882)),
        ),
    ]
