# Generated by Django 5.0.1 on 2024-02-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_promos_alter_item_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.ManyToManyField(blank=True, default=None, to='shop.promo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 19, 23, 393724)),
        ),
    ]
