# Generated by Django 5.0.1 on 2024-02-22 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_promos_alter_item_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='Customer A', max_length=24),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 29, 13, 253593)),
        ),
    ]
