# Generated by Django 5.0.1 on 2024-02-22 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_customer_alter_item_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='lines',
            field=models.ManyToManyField(blank=True, default=None, to='shop.orderline'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_code',
            field=models.CharField(default='code', max_length=24),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 17, 57, 33, 86371)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='promo_code',
            field=models.CharField(blank=True, default=None, max_length=12),
        ),
    ]
