# Generated by Django 5.0.2 on 2024-03-07 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_item_created_on_alter_orderline_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 47, 19, 113410, tzinfo=datetime.timezone.utc)),
        ),
    ]
