# Generated by Django 5.0.2 on 2024-03-07 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_item_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 18, 50, 44, 845712, tzinfo=datetime.timezone.utc)),
        ),
    ]
