# Generated by Django 5.0.3 on 2024-03-23 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_item_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 9, 24, 35, 850462, tzinfo=datetime.timezone.utc)),
        ),
    ]
